OutputDevice: Speakers (High Definition Audio Device)
Latency: 50
MasterVolume:
  Enabled: true
  Value: -3
Engine:
  Enabled: true
  Value: -21
LandingGear:
  Enabled: true
  Value: -12
Bumps:
  Enabled: true
  Value: -9
Flaps:
  Enabled: true
  Value: -15
RollRate:
  Enabled: true
  Value: -18
GForces:
  Enabled: true
  Value: -15
StallBuffet:
  Enabled: true
  Value: -9
Impacts:
  Enabled: true
  Value: 0
HitsReceived:
  Enabled: true
  Value: -12
Gunfire:
  Enabled: true
  Value: -10
OrdnanceRelease:
  Enabled: true
  Value: 0
DebugLogging: true
LowPassFilter:
  Enabled: false
  Value: 120
HighPassFilter:
  Enabled: false
  Value: 10
